// Biomes and Dimension Database for DinosExpansion Wiki
const DIMENSION_DATA = {
  name: "The Ark-Grid Sector",
  sectorId: "SECTOR-B9",
  description: "The Ark-Grid Sector is a newly discovered pocket dimension generated by a localized anomaly in the Obelisk mainframe. It functions as an experimental testing ground with intensified gravity, unique atmospheric pressures, and extreme environmental biomes. Here, dinosaurs exhibit enhanced stats, altered behaviors, and specialized spawn patterns suitable for survivors looking for high-risk, high-reward hunting.",
  biomes: [
    {
      id: "redwood",
      name: "Redwood Canopy",
      hazardLevel: "Medium",
      image: "assets/images/redwood.png",
      description: "A dense, ancient woodland dominated by massive, towering redwood trees. Sunlight filters through the thick canopy, illuminating a forest floor teeming with predators. The giant redwoods are completely indestructible, making them perfect pillars for constructing secure, elevated tree platforms away from land threats.",
      spawns: [
        { name: "Tyrannosaurus Rex", spawnRate: "Rare (12%)", role: "Apex Wanderer" },
        { name: "Velociraptor", spawnRate: "Common (55%)", role: "Pack Hunter" },
        { name: "Triceratops", spawnRate: "Uncommon (25%)", role: "Grazer" },
        { name: "Pteranodon", spawnRate: "Common (45% - Canopy)", role: "Sky Scout" }
      ],
      features: [
        { name: "Giant Redwood Trees", detail: "Towering, indestructible trees that can support heavy wooden and metal Tree Platforms." },
        { name: "Redwood Sap Harvesting", detail: "Survivors can attach Tree Sap Taps to redwoods to slowly harvest Sap, a critical ingredient in Superior/Exceptional Kibbles and medical brews." },
        { name: "Elevated Cross-Travel", detail: "A series of zip-lines and rope bridges can be constructed between trees, enabling travelers to completely avoid ground predators." }
      ]
    },
    {
      id: "caverns",
      name: "Bioluminescent Abyssal Caverns",
      hazardLevel: "High / Extreme",
      image: "assets/images/caverns.png",
      description: "A massive subterranean cave system illuminated by glowing flora and raw element deposits. The environment is hot, humid, and filled with radioactive pockets. Navigating these caves requires caution, as the bioluminescent moss obscures pit falls, toxic pools, and camouflaged predators.",
      spawns: [
        { name: "Spinosaurus", spawnRate: "Uncommon (20% - Riverways)", role: "Semi-Aquatic Guardian" },
        { name: "Ankylosaurus", spawnRate: "Common (40% - Crystal Ridges)", role: "Ore Breaker" },
        { name: "Velociraptor", spawnRate: "Common (60% - Dark Tunnels)", role: "Cave Pouncer" }
      ],
      features: [
        { name: "Raw Element Crystals", detail: "Crystals emitting neon light that can be mined for Raw Element, the core energy source for futuristic TEK gear." },
        { name: "Bioluminescent Flora", detail: "Exotic glowing mushrooms and flowers that can be harvested for Bio-Toxins, Narco-Spores, and organic dyes." },
        { name: "Radioactive Thermal Pools", detail: "Warm rivers that speed up stamina recovery but inflict minor radiation damage unless wearing protective hazard gear." }
      ]
    }
  ]
};

// Export if in Node context, otherwise define globally
if (typeof module !== "undefined" && module.exports) {
  module.exports = { DIMENSION_DATA };
} else {
  window.DIMENSION_DATA = DIMENSION_DATA;
}
